### ISSUE TITLE
Can I define a global function in controller?

### ISSUE THREAD

**Issue by kuoruan** [seamustuohy/luci_tutorials#6]
So that I can call it in cbis?

**Comment by seamustuohy** [comment]
If you want to use a function in your CBI's I would write a module and require them from the CBI files. This makes it easier to re-use the function across multiple CBI files. 

Here is an example of this:

* I made [a module that validates different types of inputs.](https://github.com/opentechinstitute/luci-commotion/blob/master/modules/validate.lua) 
* When I installed my package I had it install to `/usr/lib/lua/luci/commotion/validate.lua` 
* I [`require` it in my cbis](https://github.com/opentechinstitute/luci-commotion/blob/master/luasrc/model/cbi/commotion/app_settings.lua#L4). 
* I used the [app_category function from the validate module](https://github.com/opentechinstitute/luci-commotion/blob/master/modules/validate.lua#L123-L138) to validate [the category listing provided in the app_setting menu](https://github.com/opentechinstitute/luci-commotion/blob/master/luasrc/model/cbi/commotion/app_settings.lua#L14).

**Comment by kuoruan** [comment]
OK, Thank you very much.
