### ISSUE TITLE
Markdown issue on Title on 01 Introduction

### ISSUE THREAD

**Issue by iggirex** [seamustuohy/luci_tutorials#8]
I'm following along with the video, and in the video the title looks properly formatted, however on my computer it looks like this

`Basic LuCI development Info ===========================
`

**Comment by seamustuohy** [comment]
Thanks!

Fixed in https://github.com/seamustuohy/luci_tutorials/commit/8fd993eff962fd51503de68aa1e69b3cdd5ce5c7
